# Multiclass classification/ Phân loại nhiều lớp

## Import motdules

In [48]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.callbacks import EarlyStopping

## Load dataset

In [49]:
df = pd.read_csv('../data/fetal_health.csv')
df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability  

In [51]:
df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [52]:
X = df.drop('fetal_health', axis=1)
X.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                               43.0       ...   
1                                                0.0       ...   
2                                                0.0       ...   
3                                                0.0       ...   
4                                                0.0       ...   

   histogram_width  histogram_min  histogram_max  histogram_number_of_peaks  \
0             64.0           62.0          126.0                        2.0   
1            130.0           68.0          198.0                        6.0   
2            130.0           68.0          198.0                        5.0   
3            117.0           53.0          170.0                       11.0   
4            117.0           53.0          170.0                        9.0   

   histogram_number_of_zeroes  histogram_mode  histogram_mean  \
0                         0.0           120.0           137.0   
1                         1.0           141.0           136.0   
2                         1.0           141.0           135.0   
3                         0.0           137.0           134.0   
4                         0.0           137.0           136.0   

   histogram_median  histogram_variance  histogram_tendency  
0             121.0                73.0                 1.0  
1             140.0                12.0                 0.0  
2             138.0                13.0                 0.0  
3             137.0                13.0                 1.0  
4             138.0                11.0                 1.0  

[5 rows x 21 columns]

## Mã hoá lại y

In [53]:
target_names = df['fetal_health'].unique()
target_names

array([2., 1., 3.])

In [54]:
target_dict = {n:i for i, n in enumerate(target_names)}
target_dict

{2.0: 0, 1.0: 1, 3.0: 2}

In [55]:
y= df['fetal_health'].map(target_dict)
y.head(10)

0    0
1    1
2    1
3    1
4    1
5    2
6    2
7    2
8    2
9    2
Name: fetal_health, dtype: int64

In [56]:
from tensorflow.keras.utils import to_categorical

In [57]:
y_cat = to_categorical(y, dtype = int)

In [58]:
y_cat[:10]

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

### Train test split

In [60]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y_cat,
                                                    test_size=0.2,
                                                   random_state=10)

## Tạo model

In [88]:
model = Sequential()
model.add(Dense(64, input_shape=(21,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
# model.add(Dense(100, activation='relu'))
# model.add(Dense(12, activation='relu'))
# model.add(Dense(10, activation='relu'))
# model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_47 (Dense)             (None, 64)                1408      
_________________________________________________________________
dense_48 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_49 (Dense)             (None, 32)                2080      
_________________________________________________________________
dense_50 (Dense)             (None, 3)                 99        
Total params: 7,747
Trainable params: 7,747
Non-trainable params: 0
_________________________________________________________________


In [91]:
model.fit(X_train, y_train, epochs=150, validation_split=0.1)

Epoch 1/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2568 - accuracy: 0.9039 - val_loss: 0.3075 - val_accuracy: 0.8941
Epoch 2/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2621 - accuracy: 0.8941 - val_loss: 0.3375 - val_accuracy: 0.8765
Epoch 3/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2490 - accuracy: 0.9026 - val_loss: 0.2948 - val_accuracy: 0.9118
Epoch 4/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2375 - accuracy: 0.9098 - val_loss: 0.2989 - val_accuracy: 0.9118
Epoch 5/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2462 - accuracy: 0.9052 - val_loss: 0.4196 - val_accuracy: 0.8353
Epoch 6/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2767 - accuracy: 0.8869 - val_loss: 0.3173 - val_accuracy: 0.8706
Epoch 7/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2655 - accuracy: 0.8954 - val_loss: 0.2906 - val_accuracy: 0.9176
Epoch 8/150
4

Epoch 59/150
48/48 [==============================] - 0s 6ms/step - loss: 0.2181 - accuracy: 0.9131 - val_loss: 0.3377 - val_accuracy: 0.8529
Epoch 60/150
48/48 [==============================] - 0s 6ms/step - loss: 0.1979 - accuracy: 0.9170 - val_loss: 0.2719 - val_accuracy: 0.9235
Epoch 61/150
48/48 [==============================] - 0s 5ms/step - loss: 0.2154 - accuracy: 0.9085 - val_loss: 0.3383 - val_accuracy: 0.9000
Epoch 62/150
48/48 [==============================] - 0s 5ms/step - loss: 0.1944 - accuracy: 0.9176 - val_loss: 0.3230 - val_accuracy: 0.9059
Epoch 63/150
48/48 [==============================] - 0s 6ms/step - loss: 0.2030 - accuracy: 0.9209 - val_loss: 0.3096 - val_accuracy: 0.9000
Epoch 64/150
48/48 [==============================] - 0s 6ms/step - loss: 0.2045 - accuracy: 0.9131 - val_loss: 0.2736 - val_accuracy: 0.8882
Epoch 65/150
48/48 [==============================] - 0s 5ms/step - loss: 0.1932 - accuracy: 0.9235 - val_loss: 0.3221 - val_accuracy: 0.9000
Epoch 

48/48 [==============================] - 0s 6ms/step - loss: 0.2025 - accuracy: 0.9209 - val_loss: 0.3460 - val_accuracy: 0.8941
Epoch 117/150
48/48 [==============================] - 0s 6ms/step - loss: 0.2011 - accuracy: 0.9124 - val_loss: 0.3626 - val_accuracy: 0.8941
Epoch 118/150
48/48 [==============================] - 0s 5ms/step - loss: 0.1634 - accuracy: 0.9255 - val_loss: 0.2842 - val_accuracy: 0.8882
Epoch 119/150
48/48 [==============================] - 0s 6ms/step - loss: 0.1684 - accuracy: 0.9261 - val_loss: 0.3278 - val_accuracy: 0.8706
Epoch 120/150
48/48 [==============================] - 0s 6ms/step - loss: 0.1615 - accuracy: 0.9333 - val_loss: 0.3153 - val_accuracy: 0.9059
Epoch 121/150
48/48 [==============================] - 0s 6ms/step - loss: 0.1550 - accuracy: 0.9405 - val_loss: 0.2992 - val_accuracy: 0.8882
Epoch 122/150
48/48 [==============================] - 0s 6ms/step - loss: 0.1666 - accuracy: 0.9268 - val_loss: 0.3587 - val_accuracy: 0.8941
Epoch 123/150

In [92]:
y_pred = model.predict(X_test)

In [93]:
y_pred[:5]

array([[8.1144964e-07, 9.9999917e-01, 4.3045111e-13],
       [1.5227258e-05, 9.9998474e-01, 5.2565400e-12],
       [4.9924100e-13, 4.6020587e-09, 1.0000000e+00],
       [3.0909810e-05, 9.9996912e-01, 2.7458877e-12],
       [3.9012042e-01, 6.0987502e-01, 4.5702768e-06]], dtype=float32)

In [94]:
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [95]:
from sklearn.metrics import classification_report

In [96]:
print(classification_report(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       0.80      0.70      0.75        61
           1       0.96      0.96      0.96       336
           2       0.82      0.97      0.89        29

    accuracy                           0.92       426
   macro avg       0.86      0.88      0.87       426
weighted avg       0.92      0.92      0.92       426



In [97]:
from sklearn.metrics import accuracy_score, confusion_matrix
confusion_matrix(y_test_class, y_pred_class)

array([[ 43,  14,   4],
       [ 11, 323,   2],
       [  0,   1,  28]], dtype=int64)

In [98]:
from sklearn.metrics import log_loss
log_loss(y_test_class, y_pred)

0.22011850082459386

In [99]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss: " + str(loss));
print("Accuracy: " + str(accuracy));

14/14 [==============================] - 0s 4ms/step - loss: 0.2201 - accuracy: 0.9249
Loss: 0.22011850774288177
Accuracy: 0.9248826503753662
