# Multiclass classification/ Phân loại nhiều lớp với DNN

## Import motdules

In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD, Adam
from tensorflow.keras.callbacks import EarlyStopping

## Load dataset

In [2]:
df = pd.read_csv('../data/fetal_health.csv')
df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2126 entries, 0 to 2125
Data columns (total 22 columns):
 #   Column                                                  Non-Null Count  Dtype  
---  ------                                                  --------------  -----  
 0   baseline value                                          2126 non-null   float64
 1   accelerations                                           2126 non-null   float64
 2   fetal_movement                                          2126 non-null   float64
 3   uterine_contractions                                    2126 non-null   float64
 4   light_decelerations                                     2126 non-null   float64
 5   severe_decelerations                                    2126 non-null   float64
 6   prolongued_decelerations                                2126 non-null   float64
 7   abnormal_short_term_variability                         2126 non-null   float64
 8   mean_value_of_short_term_variability  

In [4]:
df.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  histogram_min  \
0                                               43.0       ...           62.0   
1                                                0.0       ...           68.0   
2                                                0.0       ...           68.0   
3                                                0.0       ...           53.0   
4                                                0.0       ...           53.0   

   histogram_max  histogram_number_of_peaks  histogram_number_of_zeroes  \
0          126.0                        2.0                         0.0   
1          198.0                        6.0                         1.0   
2          198.0                        5.0                         1.0   
3          170.0                       11.0                         0.0   
4          170.0                        9.0                         0.0   

   histogram_mode  histogram_mean  histogram_median  histogram_variance  \
0           120.0           137.0             121.0                73.0   
1           141.0           136.0             140.0                12.0   
2           141.0           135.0             138.0                13.0   
3           137.0           134.0             137.0                13.0   
4           137.0           136.0             138.0                11.0   

   histogram_tendency  fetal_health  
0                 1.0           2.0  
1                 0.0           1.0  
2                 0.0           1.0  
3                 1.0           1.0  
4                 1.0           1.0  

[5 rows x 22 columns]

In [5]:
X = df.drop('fetal_health', axis=1)
X.head()

baseline value  accelerations  fetal_movement  uterine_contractions  \
0           120.0          0.000             0.0                 0.000   
1           132.0          0.006             0.0                 0.006   
2           133.0          0.003             0.0                 0.008   
3           134.0          0.003             0.0                 0.008   
4           132.0          0.007             0.0                 0.008   

   light_decelerations  severe_decelerations  prolongued_decelerations  \
0                0.000                   0.0                       0.0   
1                0.003                   0.0                       0.0   
2                0.003                   0.0                       0.0   
3                0.003                   0.0                       0.0   
4                0.000                   0.0                       0.0   

   abnormal_short_term_variability  mean_value_of_short_term_variability  \
0                             73.0                                   0.5   
1                             17.0                                   2.1   
2                             16.0                                   2.1   
3                             16.0                                   2.4   
4                             16.0                                   2.4   

   percentage_of_time_with_abnormal_long_term_variability  ...  \
0                                               43.0       ...   
1                                                0.0       ...   
2                                                0.0       ...   
3                                                0.0       ...   
4                                                0.0       ...   

   histogram_width  histogram_min  histogram_max  histogram_number_of_peaks  \
0             64.0           62.0          126.0                        2.0   
1            130.0           68.0          198.0                        6.0   
2            130.0           68.0          198.0                        5.0   
3            117.0           53.0          170.0                       11.0   
4            117.0           53.0          170.0                        9.0   

   histogram_number_of_zeroes  histogram_mode  histogram_mean  \
0                         0.0           120.0           137.0   
1                         1.0           141.0           136.0   
2                         1.0           141.0           135.0   
3                         0.0           137.0           134.0   
4                         0.0           137.0           136.0   

   histogram_median  histogram_variance  histogram_tendency  
0             121.0                73.0                 1.0  
1             140.0                12.0                 0.0  
2             138.0                13.0                 0.0  
3             137.0                13.0                 1.0  
4             138.0                11.0                 1.0  

[5 rows x 21 columns]

## Mã hoá lại y

In [6]:
target_names = df['fetal_health'].unique()
target_names

array([2., 1., 3.])

In [7]:
target_dict = {n:i for i, n in enumerate(target_names)}
target_dict

{2.0: 0, 1.0: 1, 3.0: 2}

In [8]:
y= df['fetal_health'].map(target_dict)
y.head(10)

0    0
1    1
2    1
3    1
4    1
5    2
6    2
7    2
8    2
9    2
Name: fetal_health, dtype: int64

In [9]:
from tensorflow.keras.utils import to_categorical

In [10]:
y_cat = to_categorical(y, dtype = int)

In [11]:
y_cat[:10]

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

### Train test split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X.values, y_cat,
                                                    test_size=0.2,
                                                   random_state=10)

## Tạo model

In [13]:
model = Sequential()
model.add(Dense(64, input_shape=(21,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
# model.add(Dense(100, activation='relu'))
# model.add(Dense(12, activation='relu'))
# model.add(Dense(10, activation='relu'))
# model.add(Dense(4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                1408      
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 99        
Total params: 7,747
Trainable params: 7,747
Non-trainable params: 0
_________________________________________________________________


In [14]:
model.fit(X_train, y_train, epochs=150, validation_split=0.1)

Epoch 1/150
48/48 [==============================] - 2s 13ms/step - loss: 5.2879 - accuracy: 0.7046 - val_loss: 0.5851 - val_accuracy: 0.8412
Epoch 2/150
48/48 [==============================] - 0s 8ms/step - loss: 0.5855 - accuracy: 0.8366 - val_loss: 0.4143 - val_accuracy: 0.8765
Epoch 3/150
48/48 [==============================] - 0s 8ms/step - loss: 0.4783 - accuracy: 0.8425 - val_loss: 0.3565 - val_accuracy: 0.8882
Epoch 4/150
48/48 [==============================] - 0s 8ms/step - loss: 0.4349 - accuracy: 0.8503 - val_loss: 0.4191 - val_accuracy: 0.8412
Epoch 5/150
48/48 [==============================] - 0s 8ms/step - loss: 0.4206 - accuracy: 0.8523 - val_loss: 0.3795 - val_accuracy: 0.8235
Epoch 6/150
48/48 [==============================] - 0s 8ms/step - loss: 0.4601 - accuracy: 0.8399 - val_loss: 0.3597 - val_accuracy: 0.9059
Epoch 7/150
48/48 [==============================] - 0s 8ms/step - loss: 0.3857 - accuracy: 0.8595 - val_loss: 0.3399 - val_accuracy: 0.8824
Epoch 8/150


48/48 [==============================] - 0s 10ms/step - loss: 0.3066 - accuracy: 0.8830 - val_loss: 0.2552 - val_accuracy: 0.9235
Epoch 59/150
48/48 [==============================] - 1s 11ms/step - loss: 0.2942 - accuracy: 0.8837 - val_loss: 0.2973 - val_accuracy: 0.8471
Epoch 60/150
48/48 [==============================] - 0s 8ms/step - loss: 0.3116 - accuracy: 0.8856 - val_loss: 0.2874 - val_accuracy: 0.9000
Epoch 61/150
48/48 [==============================] - 0s 8ms/step - loss: 0.2959 - accuracy: 0.8856 - val_loss: 0.3135 - val_accuracy: 0.9235
Epoch 62/150
48/48 [==============================] - 0s 10ms/step - loss: 0.2894 - accuracy: 0.8915 - val_loss: 0.2931 - val_accuracy: 0.8824
Epoch 63/150
48/48 [==============================] - 0s 10ms/step - loss: 0.2895 - accuracy: 0.8915 - val_loss: 0.2739 - val_accuracy: 0.9176
Epoch 64/150
48/48 [==============================] - 0s 9ms/step - loss: 0.2879 - accuracy: 0.8810 - val_loss: 0.3320 - val_accuracy: 0.8588
Epoch 65/150
48

48/48 [==============================] - 0s 8ms/step - loss: 0.2275 - accuracy: 0.9092 - val_loss: 0.2470 - val_accuracy: 0.9471
Epoch 116/150
48/48 [==============================] - 0s 9ms/step - loss: 0.2274 - accuracy: 0.9085 - val_loss: 0.3417 - val_accuracy: 0.8647
Epoch 117/150
48/48 [==============================] - 0s 10ms/step - loss: 0.2430 - accuracy: 0.9065 - val_loss: 0.4088 - val_accuracy: 0.8529
Epoch 118/150
48/48 [==============================] - 0s 10ms/step - loss: 0.2588 - accuracy: 0.8922 - val_loss: 0.2917 - val_accuracy: 0.9412
Epoch 119/150
48/48 [==============================] - 0s 9ms/step - loss: 0.2602 - accuracy: 0.8935 - val_loss: 0.3092 - val_accuracy: 0.8941
Epoch 120/150
48/48 [==============================] - 0s 9ms/step - loss: 0.2376 - accuracy: 0.9098 - val_loss: 0.3146 - val_accuracy: 0.8882
Epoch 121/150
48/48 [==============================] - 0s 10ms/step - loss: 0.2496 - accuracy: 0.9052 - val_loss: 0.3220 - val_accuracy: 0.9059
Epoch 122/

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred[:5]

array([[2.4841380e-05, 9.9997509e-01, 6.5005629e-08],
       [1.7840760e-02, 9.8215759e-01, 1.5847326e-06],
       [4.0427290e-04, 1.1863229e-03, 9.9840945e-01],
       [3.7164150e-03, 9.9628347e-01, 8.2953825e-08],
       [3.1660774e-01, 6.8293667e-01, 4.5560618e-04]], dtype=float32)

In [17]:
y_test_class = np.argmax(y_test, axis=1)
y_pred_class = np.argmax(y_pred, axis=1)

In [18]:
from sklearn.metrics import classification_report

In [19]:
print(classification_report(y_test_class, y_pred_class))

              precision    recall  f1-score   support

           0       0.63      0.56      0.59        61
           1       0.92      0.95      0.93       336
           2       0.89      0.83      0.86        29

    accuracy                           0.88       426
   macro avg       0.81      0.78      0.79       426
weighted avg       0.88      0.88      0.88       426



In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix
confusion_matrix(y_test_class, y_pred_class)

array([[ 34,  24,   3],
       [ 18, 318,   0],
       [  2,   3,  24]], dtype=int64)

In [21]:
from sklearn.metrics import log_loss
log_loss(y_test_class, y_pred)

0.26718104181619495

In [22]:
loss, accuracy = model.evaluate(X_test, y_test)
print("Loss: " + str(loss));
print("Accuracy: " + str(accuracy));

14/14 [==============================] - 0s 6ms/step - loss: 0.2672 - accuracy: 0.8826
Loss: 0.26718103885650635
Accuracy: 0.8826290965080261
